version: 2.1
anchors:
  # set_env: 再帰的な環境変数の参照や、環境変数の蓄積に使う。
  set_env: &set_env
    name: set environment
    command: . .circleci/set_env.sh

jobs:
  build_and_push_image:
    machine:
      enabled: true
    steps:
      - checkout
      - run: *set_env
      - run:
          name: build docker image
          command: docker build -t ${ECR_REPO_NAME} .
      - run:
          name: login to ECR
          command: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - run:
          name: push image to ECR
          command: |
            docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_NAME}
            docker push ${ECR_IMAGE_NAME}

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only:
                - develop
                - master
                - /^stage[0-9]+/
